version: '2'
services:
  mysql:
    build:
      context: ./mysql
      args:
        METRON_VERSION: $METRON_VERSION
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
  kafkazk:
    build:
      context: ./kafkazk
      args:
        DOCKER_HOST: $DOCKER_HOST
    ports:
      - "9092:9092"
      - "2181:2181"
  hbase:
    build:
      context: ./hbase
      args:
        METRON_VERSION: $METRON_VERSION
    ports:
      - "16010:16010"
    volumes:
      - "/opt/hbase-1.1.6/conf"
    depends_on:
      - kafkazk
  storm:
    build:
      context: ./storm
      args:
        METRON_VERSION: $METRON_VERSION
    ports:
      - "8000:8000"
      - "8080:8080"
      - "8081:8081"
    environment:
      ZOOKEEPER_ADDR: kafkazk
    volumes_from:
      - hbase
    depends_on:
      - mysql
      - kafkazk
      - hbase
      - elasticsearch
    command: --daemon nimbus supervisor ui logviewer
  elasticsearch:
    image: elasticsearch:2.3
    ports:
      - "9200:9200"
      - "9300:9300"
  kibana:
    build: ./kibana
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
